<?php

/**
 * ChatBox Class extends CWidget
 *
 *
 * @author Roman Danylchuk <skype romarob2>
 * @link http://
 * @copyright Copyright &copy; 2008-2012 
 * @license http://
 */
/**
 * ChatBox is the class for display on your pages a block for chat
 *
 *
 */
class ChatBox extends CWidget{

	/**
	 * Mantains widget defaults.
	 *
	 * @var array
	 */
	public $_options = array(
		// Unique identifier, is autogenerated by default, useful for jQuery integrations.
		'id' => false,
		// Chat poster width in pixels
		'width' => '320px',
		// Chat and poster height in pixels
		'height' => '240px',
		// Chat title
		'title' => 'chat',
		// Chat position 
		'float' => 'right',
		// Top 
		'top' => '100px',
	);
	/**
	 * Mantains widget user options.
	 *
	 * @var array
	 */
	public $options = array();

	/**
	 * Simply publish our assets.
	 */
	public function init()
	{
		$this->publishAssets();
	}


	/**
	 * Simply map our options to chat.
	 */
         public function run()
         {
                $this->renderContent();
         }

    
         /**
         * 
         * @return nothing
         * @access public
         */
         public function renderContent(){
            
             if (!isset($_POST['getmess'])){
            //get defoul user and online users list for chat
             
            $user = Yii::app()->user->isGuest?Yii::app()->user->name:'Guest';
            /*
	     * Get options
	     */
	     $this->options=$this->options+$this->_options;
	     if (!$this->options['id']) {
		$this->options['id'] = 'ChatBox_' . uniqid();
	     }
             $this->render('ChatBox',array('options'=>$this->options,'user'=>$user));
             }
             else {
                 echo 1;
             }
         }


	 protected static function publishAssets()
	 {
		$assets = dirname(__FILE__) . '/assets';
		$baseUrl = Yii::app()->assetManager->publish($assets);
		if (is_dir($assets)) {
			Yii::app()->clientScript->registerCoreScript('jquery');
			Yii::app()->clientScript->registerScriptFile($baseUrl . '/chat.js?3', CClientScript::POS_HEAD);
			Yii::app()->clientScript->registerCssFile($baseUrl . '/chat.css');
		} else {
			throw new Exception('ChatBox - Error: Couldn\'t find assets to publish.');
		}
	 }


}

?>
